services:
  tournament-app:
    container_name: testkupa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_SECRET=${ADMIN_SECRET}
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    restart: unless-stopped    
    networks:
      - next
volumes:
  data:

networks:
  next:
    external: true